apiVersion: v1
kind: ServiceAccount
metadata:
  name: swiss-army-knife
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiss-army-knife
spec:
  strategy:
    type: Recreate
  replicas: 3
  selector:
    matchLabels:
      app: swiss-army-knife
  template:
    metadata:
      labels:
        app: swiss-army-knife
    spec:
      serviceAccountName: swiss-army-knife
      containers:
        - image: utkuozdemir/swiss-army-knife:v0.4.0
          name: swiss-army-knife
      terminationGracePeriodSeconds: 0
