apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: swiss-army-knife
spec:
  allowPrivilegeEscalation: true
  allowedCapabilities:
    - '*'
  fsGroup:
    rule: RunAsAny
  hostIPC: true
  hostNetwork: true
  hostPID: true
  hostPorts:
    - max: 65536
      min: 1
  privileged: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
    - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: swiss-army-knife-psp
rules:
  - apiGroups:
      - extensions
      - policy
    resourceNames:
      - swiss-army-knife
    resources:
      - podsecuritypolicies
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: swiss-army-knife-psp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: swiss-army-knife-psp
subjects:
  - kind: ServiceAccount
    name: swiss-army-knife
